version: '3'

services:
  clickhouse_server:
    image: yandex/clickhouse-server:21.3.20.1
    container_name: clickhouse-server_1
    hostname: clickhouse-server_1
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9004:9004" 
    volumes:
      - ./conf/users.xml:/etc/clickhouse-server/users.xml
      - /opt/clickhouse/log:/var/log/clickhouse-server/
      - /opt/clickhouse/db:/var/lib/clickhouse
    networks:
      - network1
  fastapi:
      build: app
      environment:
        - PORT=8080
      ports:
        - 8080:8080
        
  # clickhouse_client:
  #   image: yandex/clickhouse-client:21.3.20.1
  #   entrypoint:
  #     - /bin/sleep
  #   command:
  #     - infinity
  #   networks:
  #     - network1

networks:
  network1:
    driver: bridge
    ipam:
      config:
        - subnet: 10.222.1.0/24
