FROM tiangolo/uvicorn-gunicorn:python3.9

LABEL maintainer="Wu, Shao-Kai <lastkie@gmail.com>"

COPY ./trailchecker/requirements.txt /tmp/requirements.txt
RUN pip install --no-cache-dir -r /tmp/requirements.txt

COPY ./trailchecker /app
